# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barrapunto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pages',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pages',
            old_name='url',
            new_name='page',
        ),
    ]
