# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barrapunto', '0002_auto_20160506_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barrapunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('link', models.TextField()),
            ],
        ),
    ]
